### PR TITLE
Git/week1

### PR DESCRIPTION
**Pull request by shanhaider23**
git homework week1

### CODE REVIEW

**Review by ricardoaguiar — CHANGES_REQUESTED** [review]
Hi Shanhaider, 

You have conflicts on your PR. You need to resolve them before I can approve it. 
If you have any questions, you can post them on the class channel or on the git support channel.

**Comment by shanhaider23** [comment]
Hi Thanks for the review. I tried to fix it. can you see it?

**Review by ricardoaguiar — APPROVED** [review]
Good Job.

**Comment by shanhaider23** [comment]
Merging Done

**Pull request merged**
