### PR TITLE
Feature/veggies

### PR DESCRIPTION
**Pull request by shanhaider23**

### CODE REVIEW

**Comment by KavyaReddy732** [comment]
Here are some changes,
1.after pulling the latest changes made on GitHub locally(computer) you need to merge the changes with feature/veggies branch(cmd: git merge <branchname>).
2.the PR should be made between git/week2 and feature/veggies.

**Comment by shanhaider23** [comment]
Hi, I did exactly the same. I made changes in GitHub and pull it and merged it with changes made on the computer.

**Comment by KavyaReddy732** [comment]
Hi Shan, I’m sorry but you PR is between master and feature/veggies. But it should be between git/week2 and feature/veggies. 
and if you follow every step in homework you’ll get something like this in your PR
A51ACE44-A653-416C-AACB-8F8A6BEC415D

**Comment by shanhaider23** [comment]
Thanks, I understand it now. I changed it. is it ok or can I repeat all the steps again by closing this pull request making another?

**Comment by KavyaReddy732** [comment]
Yes.

**Comment by shanhaider23** [comment]
i will make new pull request from start

**Pull request closed without merging**
